# Generated by Django 4.2.7 on 2025-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='tta_probs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
