# Generated by Django 4.2.7 on 2025-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0003_remove_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blast_percentage',
            field=models.FloatField(blank=True, help_text='Blast percentage (%)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytogenetics',
            field=models.CharField(blank=True, help_text='Cytogenetic risk (e.g., t(9;22), normal, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobin',
            field=models.FloatField(blank=True, help_text='Hemoglobin (g/dL)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelets',
            field=models.FloatField(blank=True, help_text='Platelet count (K/µL)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Risk'), ('HIGH', 'High Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='wbc_count',
            field=models.FloatField(blank=True, help_text='White blood cell count (K/µL)', null=True),
        ),
        migrations.CreateModel(
            name='SurvivalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(blank=True, help_text='Computed risk score from Cox model', null=True)),
                ('risk_group', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('INTERMEDIATE', 'Intermediate Risk'), ('HIGH', 'High Risk')], max_length=20, null=True)),
                ('predicted_survival_months', models.FloatField(blank=True, help_text='Predicted median survival in months', null=True)),
                ('model_features', models.JSONField(blank=True, help_text='Dictionary of features used and their coefficients', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survival_analysis', to='detection_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('event_status', models.CharField(choices=[('ALIVE', 'Alive (censored)'), ('RELAPSE', 'Relapsed'), ('DEATH', 'Death')], default='ALIVE', max_length=20)),
                ('survival_days', models.IntegerField(help_text='Days from diagnosis to event or last follow-up')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='detection_app.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
                'unique_together': {('patient', 'visit_date')},
            },
        ),
    ]
