# Generated by Django 4.2.7 on 2025-11-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0004_patient_blast_percentage_patient_cytogenetics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionresult',
            name='tta_probs',
        ),
    ]
