# Generated by Django 4.2.7 on 2025-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0005_remove_detectionresult_tta_probs'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='annotated_image',
            field=models.ImageField(blank=True, help_text='Image with detection boxes', null=True, upload_to='annotated_images/'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='cell_count',
            field=models.IntegerField(blank=True, help_text='Number of detected cells', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='cell_density',
            field=models.FloatField(blank=True, help_text='Cell density (cells per million pixels)', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='cell_statistics',
            field=models.JSONField(blank=True, help_text='Cell area, intensity, circularity statistics', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='detection_masks',
            field=models.JSONField(blank=True, help_text='Cell segmentation masks', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='concordance_index',
            field=models.FloatField(blank=True, help_text='Model C-index (discrimination ability)', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='hazard_ratios',
            field=models.JSONField(blank=True, help_text='Hazard ratios for each feature', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='l1_ratio',
            field=models.FloatField(default=1.0, help_text='L1/L2 ratio for elastic net (1.0=LASSO)'),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='model_type',
            field=models.CharField(choices=[('cph', 'Cox Proportional Hazards'), ('weibull', 'Weibull AFT'), ('loglogistic', 'Log-Logistic AFT')], default='cph', max_length=20),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='penalizer_value',
            field=models.FloatField(blank=True, help_text='LASSO penalizer (lambda)', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='survival_probability_12m',
            field=models.FloatField(blank=True, help_text='12-month survival probability', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='survival_probability_24m',
            field=models.FloatField(blank=True, help_text='24-month survival probability', null=True),
        ),
        migrations.AddField(
            model_name='survivalanalysis',
            name='survival_probability_60m',
            field=models.FloatField(blank=True, help_text='60-month survival probability', null=True),
        ),
    ]
