# Generated by Django 5.2.6 on 2025-11-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0006_detectionresult_annotated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='all_fab_classification',
            field=models.CharField(blank=True, choices=[('L1', 'L1 - Small uniform cells'), ('L2', 'L2 - Large heterogeneous cells'), ('L3', 'L3 - Large, heavily vacuolated cells (Burkitt-like)')], help_text='FAB classification for ALL (L1, L2, L3)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='aml_fab_classification',
            field=models.CharField(blank=True, choices=[('M0', 'M0 - Undifferentiated AML'), ('M1', 'M1 - AML with minimal differentiation'), ('M2', 'M2 - AML with differentiation'), ('M3', 'M3 - Acute Promyelocytic Leukemia (APL)'), ('M4', 'M4 - Acute Myelomonocytic Leukemia'), ('M5', 'M5 - Acute Monocytic Leukemia'), ('M6', 'M6 - Acute Erythroid Leukemia'), ('M7', 'M7 - Acute Megakaryocytic Leukemia')], help_text='FAB classification for AML (M0-M7)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='fab_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for FAB classification (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='leukemia_type',
            field=models.CharField(blank=True, choices=[('ALL', 'Acute Lymphoblastic Leukemia'), ('AML', 'Acute Myeloid Leukemia'), ('CLL', 'Chronic Lymphocytic Leukemia'), ('CML', 'Chronic Myeloid Leukemia'), ('NORMAL', 'Normal/Healthy')], help_text='Detected leukemia type (ALL, AML, CLL, CML, or Normal)', max_length=20, null=True),
        ),
    ]
